# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language - English
en:
  languageCode: en-us
  languageName: English
  contentDir: content/en
  title: "Matias Köhler | Botanizing everywhere"
  weight: 1
  params:
    description: "Personal website of botanist Prof. Matias Köhler"
    header:
      navbar:
        logo:
          text: "🌳🌴🌿 Botanizing everywhere"

# Portuguese (Brazil)
pt:
  languageCode: pt
  languageName: Português
  contentDir: content/pt
  title: "Matias Köhler | Botanizando em todo lugar"
  weight: 2
  params:
    description: "Site pessoal do botânico Prof. Matias Köhler"
    header:
      navbar:
        logo:
          text: "🌳🌴🌿 Botanizando em todo lugar"
  menu:
    main:
      - name: Bio
        url: /pt/
        weight: 10
      - name: Publicações
        url: /pt/publication/
